name = "EBayes"
uuid = "bad9efff-1a8e-41fb-9e7d-5d6f530fb0a3"
authors = ["Nikos Ignatiadis <nikos.ignatiadis01@gmail.com>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
MLDataPattern = "9920b226-0b2a-5f5f-9153-9aa70a013f8b"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
MLJBase = "a7f614a8-145f-11e9-1d2a-a57a1082229d"
NLSolversBase = "d41bc354-129a-5804-8e4c-c37616107c6c"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"

[compat]
julia = "1.2, 1.3, 1.4"
Distributions = "^0.21"
MLDataPattern = "^0.5"
MLJ = "^0.5"
MLJBase = "^0.7"
NLSolversBase = "^7"
Optim = "^0.19"
Reexport = "^0.2"
StatsBase = "^0.32"
StructArrays = "^0.4"